### ISSUE TITLE
taro1.3.0-beta.1转为h5时报错 useState不是个函数

### ISSUE THREAD

**Issue by ZhangJian-3ti** [NervJS/taro#3009]
**问题描述**
[类似#2982]

**复现步骤**
[复现问题的步骤]
1.npm run dev:h5
2.
```js
const [count, setCount] = useState(0)
```
**期望行为**
正常运行

**报错信息**
Uncaught (in promise) TypeError: _tarojs_taro_h5__WEBPACK_IMPORTED_MODULE_1__.default.useState is not a function
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.0-beta.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.0.0 - C:\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\nodejs\npm.CMD
 - 报错平台 [h5, weapp]

**补充信息**
代码被转换成了这样：
```js
import Taro, { useState} from "@tarojs/taro-h5";
```
hot reload的时候会出错。

**Comment by Littly** [comment]
收到 我看下

**Comment by xuanmiao-zero** [comment]
补充信息：
使用：import Taro, { Component, useState } from '@tarojs/taro'
console.log('====useState', useState)
yarn dev:h5
报错
tarojs_taro_h5__WEBPACK_IMPORTED_MODULE_1__.default.useState is not a function
    at useStore (webpack-internal:///./.temp/store/store.js:28)
    at FilterLink.render (webpack-internal:///./.temp/components/link.js:39)
    at eval (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1732)
    at errorCatcher (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1643)
    at renderComponent (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1731)
    at mountComponent (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1704)
    at ComponentWrapper.init (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:2058)
    at createElement (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1410)
    at mountChild (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1475)
    at mountVNode$1 (webpack-internal:///./node_modules/nervjs/dist/index.esm.js:1462)

**Comment by ZhangJian-3ti** [comment]
Is it possible that they all relay on the same version that we specified in package.json? Now seems every package use their own version, it's really annoying to got problems caused by inconsistent versions.

**Comment by ZhangJian-3ti** [comment]
@yuche After upgrade the @taro-components dependencies to 1.40 it did resolve the [renderIntoDocument issue](https://github.com/NervJS/nerv/issues/121), but this issue still stays the same.

**Comment by yuche** [comment]
@Littly dirty brother will help us deal with this issue.

**Comment by ZhangJian-3ti** [comment]
@yuche Thanks a lot.
@Littly 
After digged into the h5 package, compare to the weapp package, found it's missing some exports.

**Comment by ZhangJian-3ti** [comment]
After all, it works well in H5 build & hot reload mode, but there is one last thing left, it's still doesn't work in jest testing mode, so I guess that should be another issue.

**Comment by johnbian** [comment]
taro1.3.0-beta.2 运行h5 也会出现`TypeError: _tarojs_taro_h5__WEBPACK_IMPORTED_MODULE_1__.default.useState is not a function`打印了一下，`useState:undefined`。

**Comment by lyon007** [comment]
taro1.3.0-beta.2    h5 模式下dev 也是一样的错。
就是一段简单的代码
代码如下
```
import Taro,{ useState } from '@tarojs/taro';
import { View, Button} from '@tarojs/components';

function Index() {
  const [count, setCount] = useState(0);
  return (
    <View>
      Count: {count}
      <Button onClick={() => setCount(0)}>Reset</Button>
      <Button onClick={() => setCount(prevCount => prevCount + 1)}>+</Button>
      <Button onClick={() => setCount(prevCount => prevCount - 1)}>-</Button>
    </View>
  );
}

export default Index;
```

报错如下：

![image](https://user-images.githubusercontent.com/21033119/57907296-9a9b7500-78af-11e9-9da9-5506fb8f6ada.png)

**Comment by johnbian** [comment]
thx 可以了。

**Comment by ybingyu** [comment]
> taro1.3.0-beta.2 h5 模式下dev 也是一样的错。
我也是。。上面的操作似乎不起作用吧

**Comment by ybingyu** [comment]
升级到1.3.0-beta.3 并且peerDependencies "nervjs": "^1.4.0-beta.4" 。可以了
